### ISSUE TITLE
Fails on debian jessie when installing dependencies

### ISSUE THREAD

**Issue by bnvk** [firstlook/sigbin#7]
Here's the stacktrace from running `pip install -r requirements.txt`

```
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-x86_64-2.7/markupsafe/_speedups.o
Traceback (most recent call last):
  File "/home/user/sigbin/env/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/user/sigbin/env/local/lib/python2.7/site-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/home/user/sigbin/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 156, in main
    logger.fatal('Exception:\n%s' % format_exc())
  File "/home/user/sigbin/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 180, in format_exc
    traceback.print_exception(*exc_info, **dict(file=out))
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/home/user/sigbin/env/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/home/user/sigbin/env/lib/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
  File "/home/user/sigbin/env/lib/python2.7/linecache.py", line 127, in updatecache
    with open(fullname, 'rU') as fp:
SystemError: ../Objects/methodobject.c:120: bad argument to internal function
```

**Comment by garrettr** [comment]
This type of error (from compiling a C extension to a Python package) is often the result of missing or conflicting packages that contain Python development headers. Do you have the `python-dev` Debian package installed?

**Comment by bnvk** [comment]
@garrettr yes, I have that package installed already! Anything else I can offer to help debug?

**Comment by conorsch** [comment]
@bnvk Having trouble reproducing. I tried testing with a Debian 8 Vagrant VM:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python-pip
    sudo pip install virtualenv
    cd /vagrant
    virtualenv env
    source env/bin/activate
    pip install -r requirements.txt
  SHELL
end
```

Worked without problems for me. Also tested on a Debian 8 DigitalOcean droplet, and again, no problems.

Try destroying your virtualenv (`rm -rf env`) and recreating it. The traceback indicates the problem is with a file inside the venv, so there's no reason to suspect your system Python.
